apiVersion: v2
name: wren
description: Wren HPC Job Scheduler for Kubernetes — a Slurm-inspired gang scheduler with MPI support
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - hpc
  - mpi
  - scheduler
  - kubernetes
home: https://github.com/miguelgila/wren
sources:
  - https://github.com/miguelgila/wren
maintainers:
  - name: miguelgila
    url: https://github.com/miguelgila
